server:
  port: 80
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/register
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/contents
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/contents/{contentId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/score
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/rating
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/rating/{ratingId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/enrolment
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - UserFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/matching
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/contents
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - LecturerFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/score/{userId}
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - LecturerFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}/rating
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - UserFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures/{lectureId}
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lectures
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AdminFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}/comments
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}/comments/{commentId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}/{commentId}
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/articles/{articleId}
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - AllFilter
token:
  secret: www.codestates.com